# GitHub Actions workflow to build the dnsmasq-full package for Xiaomi AX3600
# This uses the OpenWrt 24.10 branch with IPSet support enabled
name: Build dnsmasq-full (Xiaomi AX3600)

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build:
    runs-on: ubuntu-22.04  # Use Ubuntu 22.04 runner
    steps:
      - name: Checkout OpenWrt source
        uses: actions/checkout@v4
        # Check out the repository (fork of OpenWrt 24.10 branch)

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache libncurses5-dev libncursesw5-dev \
              zlib1g-dev gawk flex quilt bison libelf-dev libssl-dev openssl xsltproc \
              libxml-parser-perl wget python3-distutils python3-setuptools python3-dev \
              git subversion swig time
        # Ensure all required host packages are installed for the build

      - name: Update and install OpenWrt feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
        # Pull in all package feeds (including dnsmasq-full)

      - name: Configure target and packages
        run: |
          # Set the target system to Qualcomm IPQ807x (Xiaomi AX3600)
          echo "CONFIG_TARGET_ipq807x=y" > .config
          echo "CONFIG_TARGET_ipq807x_generic=y" >> .config
          echo "CONFIG_TARGET_ipq807x_generic_DEVICE_xiaomi_ax3600=y" >> .config
          # Enable dnsmasq-full package with IPSet support, disable default dnsmasq
          echo "CONFIG_PACKAGE_dnsmasq-full=y" >> .config
          echo "CONFIG_PACKAGE_dnsmasq_full_ipset=y" >> .config
          echo "# CONFIG_PACKAGE_dnsmasq is not set" >> .config
          # Finalize the configuration
          make defconfig
        # Generate .config with target/device and package selections, then finalize it

      - name: Build and install toolchain
        run: |
          # Create symlinks for openssl and libdeflate-gzip to avoid known build issues
          make toolchain/clean
          make toolchain/install
        # Provide host tool symlinks to prevent build errors related to openssl/libdeflate

      - name: Build dnsmasq-full package
        run: make -j$(nproc) package/dnsmasq-full/compile V=s
        # Compile only the dnsmasq-full package (parallel build with verbosity)

      - name: Upload dnsmasq-full .ipk artifact
        uses: actions/upload-artifact@v4
        with:
          name: dnsmasq-full_ipk
          path: bin/packages/**/dnsmasq-full*.ipk
        # Upload the generated .ipk file as a workflow artifact
